-- Baseline correspondant au schema genere jusqu'ici par Hibernate en
-- ddl-auto=update, a partir des annotations JPA de fr.collegesthelier.voyages.model.Projet.
-- A partir de cette migration, le schema est gere par Flyway (ddl-auto=validate).

CREATE TABLE projets (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                      BIGINT NOT NULL,

    nom_projet                   VARCHAR(255) NOT NULL,
    description                  TEXT,

    date_depart                  TIMESTAMP,
    date_retour                  TIMESTAMP,
    lieu_depart                  VARCHAR(255),
    lieu_retour                  VARCHAR(255),
    transport                    VARCHAR(255),

    organisme_nom                VARCHAR(255),
    organisme_telephone          VARCHAR(255),
    organisme_email              VARCHAR(255),

    organisateur_nom             VARCHAR(255),
    organisateur_email           VARCHAR(255),
    telephone_organisateur       VARCHAR(255),

    classes_concernees           VARCHAR(255),
    effectif                     INTEGER,

    cout_global                  NUMERIC(10, 2),
    cout_par_eleve               NUMERIC(10, 2),
    montant_subvention           NUMERIC(10, 2),
    eligible_pass_culture        BOOLEAN,

    commentaire                  TEXT,

    statut                       VARCHAR(30) NOT NULL,
    motif_refus                  TEXT,

    date_validation_prof         TIMESTAMP,
    date_validation_compta       TIMESTAMP,
    date_validation_vie_scolaire TIMESTAMP,
    date_validation_direction    TIMESTAMP
);

CREATE TABLE projet_accompagnateurs (
    projet_id          BIGINT NOT NULL REFERENCES projets (id),
    nom_accompagnateur VARCHAR(255)
);
