-- Attributions de roles gerees dynamiquement par un Admin (dashboard admin),
-- en complement (jamais en remplacement) des listes d'emails de application.properties.

CREATE TABLE role_attributions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255)                NOT NULL,
    role       VARCHAR(20)                 NOT NULL,
    date_ajout TIMESTAMP                   NOT NULL,

    CONSTRAINT uk_role_attributions_email_role UNIQUE (email, role)
);
