-- Journal d'audit (dashboard admin). Pas de contrainte de cle etrangere vers
-- projets : le journal doit survivre a la suppression definitive d'un dossier.

CREATE TABLE journal_entrees (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_evenement TIMESTAMP    NOT NULL,
    auteur_email   VARCHAR(255),
    action         VARCHAR(255) NOT NULL,
    projet_id      BIGINT,
    projet_nom     VARCHAR(255),
    detail         TEXT
);
