-- Fil de commentaires sur un dossier (echanges entre organisateur et
-- valideurs, independants du motif de refus). Pas de cle etrangere vers
-- projets : coherent avec journal_entrees, la suppression des commentaires
-- d'un dossier est geree explicitement par l'application (voir
-- ProjetService.supprimerDefinitivement) avant celle du projet.
CREATE TABLE commentaires (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projet_id           BIGINT NOT NULL,
    auteur_email        VARCHAR(255) NOT NULL,
    auteur_role         VARCHAR(50),
    texte               TEXT NOT NULL,
    date_creation       TIMESTAMP NOT NULL,
    date_modification   TIMESTAMP
);

CREATE INDEX idx_commentaires_projet_id ON commentaires (projet_id);
